/**
 * Font family library shared by every text-rendering block (Heading,
 * RichText, CTAButton — see the `fontFamily` prop on each in registry.ts).
 * "System" fonts render with zero extra network cost (already on the
 * device); "Google" fonts are loaded on demand by GoogleFontLink in
 * apps/web only when a block actually uses one — see the note there.
 *
 * This is a curated ~150-family subset of Google's full ~1800-family
 * catalog (the popular, production-safe names spanning serif/sans/display/
 * monospace/handwriting), not the literal complete library — bundling and
 * indexing all ~1800 for a searchable dropdown is disproportionate to what
 * a chauffeur-site page builder needs, and this set already covers every
 * common use case.
 */
export const SYSTEM_FONTS = [
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Georgia",
  "Garamond",
  "Trebuchet MS",
  "Verdana",
  "Tahoma",
  "Courier New",
  "Impact",
  "Palatino",
] as const;

export const GOOGLE_FONTS = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Outfit",
  "Nunito",
  "Nunito Sans",
  "Raleway",
  "Ubuntu",
  "Work Sans",
  "Rubik",
  "Manrope",
  "DM Sans",
  "Sora",
  "Karla",
  "Mulish",
  "Josefin Sans",
  "Fira Sans",
  "PT Sans",
  "Noto Sans",
  "Barlow",
  "Heebo",
  "Space Grotesk",
  "Plus Jakarta Sans",
  "Figtree",
  "Lexend",
  "Epilogue",
  "Urbanist",
  "Hanken Grotesk",
  "Be Vietnam Pro",
  "Public Sans",
  "IBM Plex Sans",
  "Titillium Web",
  "Cabin",
  "Assistant",
  "Jost",
  "Prompt",
  "Overpass",
  "ABeeZee",
  "AR One Sans",
  "Archivo",
  "Bricolage Grotesque",
  "Instrument Sans",
  "Onest",
  "Geist",
  "Playfair Display",
  "Merriweather",
  "Lora",
  "PT Serif",
  "Noto Serif",
  "Crimson Text",
  "Cormorant Garamond",
  "Libre Baskerville",
  "EB Garamond",
  "Spectral",
  "Bitter",
  "Domine",
  "Zilla Slab",
  "Source Serif 4",
  "Frank Ruhl Libre",
  "Vollkorn",
  "Cardo",
  "Alegreya",
  "Old Standard TT",
  "Bodoni Moda",
  "Marcellus",
  "Fraunces",
  "Instrument Serif",
  "Newsreader",
  "Petrona",
  "Gelasio",
  "Oswald",
  "Bebas Neue",
  "Anton",
  "Archivo Black",
  "Abril Fatface",
  "Righteous",
  "Passion One",
  "Alfa Slab One",
  "Fjalla One",
  "Staatliches",
  "Big Shoulders Display",
  "Unbounded",
  "Syne",
  "Clash Display",
  "Bungee",
  "Monoton",
  "Pacifico",
  "Dancing Script",
  "Great Vibes",
  "Satisfy",
  "Caveat",
  "Sacramento",
  "Kalam",
  "Shadows Into Light",
  "Indie Flower",
  "Amatic SC",
  "Permanent Marker",
  "Courgette",
  "Cookie",
  "Parisienne",
  "Allura",
  "Tangerine",
  "Homemade Apple",
  "Roboto Mono",
  "JetBrains Mono",
  "Fira Code",
  "Source Code Pro",
  "IBM Plex Mono",
  "Space Mono",
  "Inconsolata",
  "Ubuntu Mono",
  "Noto Sans JP",
  "Noto Sans KR",
  "Noto Sans SC",
  "Cairo",
  "Tajawal",
  "Almarai",
  "El Messiri",
  "Vazirmatn",
  "Comfortaa",
  "Quicksand",
  "Baloo 2",
  "Varela Round",
  "Signika",
  "Chivo",
  "Exo 2",
  "Orbitron",
  "Rajdhani",
  "Kanit",
  "Teko",
  "Yanone Kaffeesatz",
  "Maven Pro",
  "Catamaran",
  "Saira",
  "Red Hat Display",
  "Sarabun",
  "Mukta",
  "Hind",
  "Hind Siliguri",
  "Rowdies",
  "Patua One",
  "Cinzel",
  "Cormorant",
  "Yeseva One",
  "Playfair Display SC",
] as const;

export type SystemFont = (typeof SYSTEM_FONTS)[number];
export type GoogleFont = (typeof GOOGLE_FONTS)[number];

const GOOGLE_FONT_SET = new Set<string>(GOOGLE_FONTS);

/** True when `family` should be loaded from Google Fonts (see GoogleFontLink in apps/web) rather than assumed already installed on the device. */
export function isGoogleFont(family: string | undefined): family is GoogleFont {
  return !!family && GOOGLE_FONT_SET.has(family);
}
